name: Test FFmpeg

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Check FFmpeg
        run: |
          ffmpeg -version

      - name: Check system
        run: |
          echo "CPU:"
          nproc

          echo "RAM:"
          free -h

          echo "Disk:"
          df -h
